export const FETCH_ADS_START = "FETCH_ADS_START";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAIL = "FETCH_ADS_FAIL";
export const FETCH_AD_START = "FETCH_AD_START";
export const FETCH_AD_SUCCESS = "FETCH_AD_SUCCESS";
export const FETCH_AD_FAIL = "FETCH_AD_FAIL";

export const CREATE_NEW_AD_START = "CREATE_NEW_AD_START";
export const CREATE_NEW_AD_SUCCESS = "CREATE_NEW_AD_SUCCESS";
export const CREATE_NEW_AD_FAIL = "CREATE_NEW_AD_FAIL";

export const AD_POSTING_INIT = "AD_POSTING_INIT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

