export const FETCH_ADS_START = "FETCH_ADS_START";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAIL = "FETCH_ADS_FAIL";
export const FETCH_AD_START = "FETCH_AD_START";
export const FETCH_AD_SUCCESS = "FETCH_AD_SUCCESS";
export const FETCH_AD_FAIL = "FETCH_AD_FAIL";

export const CREATE_NEW_AD_START = "CREATE_NEW_AD_START";
export const CREATE_NEW_AD_SUCCESS = "CREATE_NEW_AD_SUCCESS";
export const CREATE_NEW_AD_FAIL = "CREATE_NEW_AD_FAIL";

export const AD_POSTING_INIT = "AD_POSTING_INIT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const FETCH_USERINFO_START = "FETCH_USERINFO_START";
export const FETCH_USERINFO_SUCCESS = "FETCH_USERINFO_SUCCESS";
export const FETCH_USERINFO_FAIL = "FETCH_USERINFO_FAIL";

export const UPDATE_USER_INFO_START = "UPDATE_USER_INFO_START";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAIL = "UPDATE_USER_INFO_FAIL";

export const FETCH_USER_ADS_START = "FETCH_USER_ADS_START";
export const FETCH_USER_ADS_SUCCESS = "FETCH_USER_ADS_SUCCESS";
export const FETCH_USER_ADS_FAIL = "FETCH_USER_ADS_FAIL";

export const FETCH_USER_ORDERS_START = "FETCH_USER_ORDERS_START";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USERS_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_FAIL = "FETCH_USERS_ORDERS_FAIL";

export const REMOVE_USER_AD_START = "REMOVE_USER_AD_START";
export const REMOVE_USER_AD_SUCCESS = "REMOVE_USER_AD_SUCCESS";
export const REMOVE_USER_AD_FAIL = "REMOVE_USER_AD_FAIL";

export const CHANGE_AD_STATUS_START = "CHANGE_AD_STATUS_START";
export const CHANGE_AD_STATUS_SUCCESS = "CHANGE_AD_STATUS_SUCCESS";
export const CHANGE_AD_STATUS_FAIL = "CHANGE_AD_STATUS_FAIL";

export const PAY_FOR_ITEM_START = "PAY_FOR_ITEM_START";
export const PAY_FOR_ITEM_SUCCESS = "PAY_FOR_ITEM_SUCCESS";
export const PAY_FOR_ITEM_FAIL = "PAY_FOR_ITEM_FAIL";

export const CLEAR_PURCHASE_STATUS = "CLEAR_PURCHASE_STATUS";
export const CLEAR_UPDATED_AD_ID = "CLEAR_UPDATED_AD_ID";