export const FETCH_ADS_START = "FETCH_ADS_START";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAIL = "FETCH_ADS_FAIL";
export const FETCH_AD_START = "FETCH_AD_START";
export const FETCH_AD_SUCCESS = "FETCH_AD_SUCCESS";
export const FETCH_AD_FAIL = "FETCH_AD_FAIL";

